Fix AttributeError in geospatial PDF header
I think when mapnik.printing switched from PyPDF to PyPDF2 it caused
this error:

>E  AttributeError: 'DictionaryObject' object has no attribute 'has_key'

This change fixes the error. String keys work just fine for these
objects, you don't need to wrap them in NameObject()